### ISSUE TITLE
New cgo pointer rules break calls to yara [go 1.6]

### ISSUE THREAD

**Issue by GitMirar** [hillu/go-yara#2]
go test fails with the following panic
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x5913e0, 0xc82000a630)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/hillu/go-yara._cgoCheckPointer0(0x553360, 0xc820010980, 0x0, 0x0, 0x0, 0x540060)
        ??:0 +0x4d
github.com/hillu/go-yara.NewCompiler(0x0, 0x0, 0x0)
        /home/alexander/go/src/github.com/hillu/go-yara/compiler.go:76 +0x2f7
github.com/hillu/go-yara.Compile(0x60fca0, 0x5d, 0x0, 0x0, 0x0, 0x0)
        /home/alexander/go/src/github.com/hillu/go-yara/compiler.go:189 +0x44
github.com/hillu/go-yara.TestMain(0xc820053ef8)
        /home/alexander/go/src/github.com/hillu/go-yara/main_test.go:9 +0x39
main.main()
        github.com/hillu/go-yara/_test/_testmain.go:100 +0x114
exit status 2
FAIL    github.com/hillu/go-yara        0.006s
```

Apparently go 1.6 enforces the rules documented at  [golang](https://tip.golang.org/cmd/cgo/#hdr-Passing_pointers) .

**Comment by hillu** [comment]
Thanks for reporting this. I am quite glad that the rules about cgo pointers have been made clearer in the documentation and that they are actually enforced by the runtime. I'm working on a fix ... and a better solution for the problem I worked around in aaf1fcac4f5af7c94d98cbb0ddbf4b16472a4679.
