### ISSUE TITLE
Assertion failed: compiler->errors == 0

### ISSUE THREAD

**Issue by blacktop** [hillu/go-yara#32]
When a rule fails to compile it causes a crash

```bash
ERRO[0000] failed to add rule to compiler: /rules/yara/yara_mixed_ext_vars.yar: undefined identifier "filename"  animal=walrus
Assertion failed: compiler->errors == 0 (compiler.c: yr_compiler_get_rules: 825)
SIGABRT: abort
PC=0x7fe370f11f1b m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fe370f11f1b
stack: frame={sp:0x7ffe3a5bee58, fp:0x0} stack=[0x7ffe3a5ac0f8,0x7ffe3a5bf120)
00007ffe3a5bed58:  00353238203a7365  0000564c0e1b74a0
00007ffe3a5bed68:  00007ffe3a5bf070  0000564c0d6e60c5 <runtime.gentraceback+6117>
00007ffe3a5bed78:  0000564c0df763e0  0000564c0e1b74a0
00007ffe3a5bed88:  0000564c0d6f0da1 <runtime.goexit+1>  00007ffe3a5bee80
00007ffe3a5bed98:  0000002200000000  00000000ffffffff
00007ffe3a5beda8:  00007ffe3a5bedf8  0000564c0d6b03f3 <runtime.sysMap+211>
00007ffe3a5bedb8:  000000c41fff0000  0000000000000001
00007ffe3a5bedc8:  0000002200000003  0000564c0d9bfbcc <github.com/maliceio/malice-yara/vendor/github.com/pkg/errors.Wrapf+236>
00007ffe3a5bedd8:  000000c42005ffe0  0000000000000000
00007ffe3a5bede8:  0000000000000000  00007ffe3a5bee38
00007ffe3a5bedf8:  0000564c0d6ac107 <runtime.persistentalloc1+439>  0000000000000007
00007ffe3a5bee08:  000000c42005f7e8  00007ffe3a5bf0a0
00007ffe3a5bee18:  ffffffffffffffff  000000000000015e
00007ffe3a5bee28:  000000000000015d  0000000000000200
00007ffe3a5bee38:  00007fe370f1456f  0000564c0d6eb647 <runtime.persistentalloc.func1+71>
00007ffe3a5bee48:  0000003000000010  0000000000000006
00007ffe3a5bee58: <00007fe370f12035  0000000000000000
00007ffe3a5bee68:  0000000000000000  0000000000000000
00007ffe3a5bee78:  00007fe370cbd628  00007fe370cbdb10
00007ffe3a5bee88:  0000000000000339  0000564c0d6c660a <runtime.main+538>
00007ffe3a5bee98:  0000005000048176  0000564c0dae699e <main.main.func2+382>
00007ffe3a5beea8:  000001f00027dd40  0000000000000000
00007ffe3a5beeb8:  0000000000000000  00007fe37115a2c0
00007ffe3a5beec8:  0000000000000000  ffffffffffffffff
00007ffe3a5beed8:  00007fe370f138fc  000000c42005f7e8
00007ffe3a5beee8:  00007fe370f1543c  ffffffffffffffff
00007ffe3a5beef8:  000000c42005f7e8  00007ffe3a5bf0a0
00007ffe3a5bef08:  00007fe370ee9fb4  ffffffffffffffff
00007ffe3a5bef18:  00007fe370eea004  0000564c0d6f0da1 <runtime.goexit+1>
00007ffe3a5bef28:  00007fe370c95163  0000000000000000
00007ffe3a5bef38:  0000000000000000  0000564c0dad2410 <github.com/maliceio/malice-yara/vendor/github.com/urfave/cli.(*App).Run+1520>
00007ffe3a5bef48:  000001d000271e03  0000000000000000
runtime: unknown pc 0x7fe370f11f1b
stack: frame={sp:0x7ffe3a5bee58, fp:0x0} stack=[0x7ffe3a5ac0f8,0x7ffe3a5bf120)
00007ffe3a5bed58:  00353238203a7365  0000564c0e1b74a0
00007ffe3a5bed68:  00007ffe3a5bf070  0000564c0d6e60c5 <runtime.gentraceback+6117>
00007ffe3a5bed78:  0000564c0df763e0  0000564c0e1b74a0
00007ffe3a5bed88:  0000564c0d6f0da1 <runtime.goexit+1>  00007ffe3a5bee80
00007ffe3a5bed98:  0000002200000000  00000000ffffffff
00007ffe3a5beda8:  00007ffe3a5bedf8  0000564c0d6b03f3 <runtime.sysMap+211>
00007ffe3a5bedb8:  000000c41fff0000  0000000000000001
00007ffe3a5bedc8:  0000002200000003  0000564c0d9bfbcc <github.com/maliceio/malice-yara/vendor/github.com/pkg/errors.Wrapf+236>
00007ffe3a5bedd8:  000000c42005ffe0  0000000000000000
00007ffe3a5bede8:  0000000000000000  00007ffe3a5bee38
00007ffe3a5bedf8:  0000564c0d6ac107 <runtime.persistentalloc1+439>  0000000000000007
00007ffe3a5bee08:  000000c42005f7e8  00007ffe3a5bf0a0
00007ffe3a5bee18:  ffffffffffffffff  000000000000015e
00007ffe3a5bee28:  000000000000015d  0000000000000200
00007ffe3a5bee38:  00007fe370f1456f  0000564c0d6eb647 <runtime.persistentalloc.func1+71>
00007ffe3a5bee48:  0000003000000010  0000000000000006
00007ffe3a5bee58: <00007fe370f12035  0000000000000000
00007ffe3a5bee68:  0000000000000000  0000000000000000
00007ffe3a5bee78:  00007fe370cbd628  00007fe370cbdb10
00007ffe3a5bee88:  0000000000000339  0000564c0d6c660a <runtime.main+538>
00007ffe3a5bee98:  0000005000048176  0000564c0dae699e <main.main.func2+382>
00007ffe3a5beea8:  000001f00027dd40  0000000000000000
00007ffe3a5beeb8:  0000000000000000  00007fe37115a2c0
00007ffe3a5beec8:  0000000000000000  ffffffffffffffff
00007ffe3a5beed8:  00007fe370f138fc  000000c42005f7e8
00007ffe3a5beee8:  00007fe370f1543c  ffffffffffffffff
00007ffe3a5beef8:  000000c42005f7e8  00007ffe3a5bf0a0
00007ffe3a5bef08:  00007fe370ee9fb4  ffffffffffffffff
00007ffe3a5bef18:  00007fe370eea004  0000564c0d6f0da1 <runtime.goexit+1>
00007ffe3a5bef28:  00007fe370c95163  0000000000000000
00007ffe3a5bef38:  0000000000000000  0000564c0dad2410 <github.com/maliceio/malice-yara/vendor/github.com/urfave/cli.(*App).Run+1520>
00007ffe3a5bef48:  000001d000271e03  0000000000000000

goroutine 1 [syscall]:
runtime.cgocall(0x564c0dae81c5, 0xc42005f7e8, 0x564c0de01b60)
	/usr/lib/go/src/runtime/cgocall.go:128 +0x66 fp=0xc42005f7b8 sp=0xc42005f780 pc=0x564c0d69c756
github.com/maliceio/malice-yara/vendor/github.com/hillu/go-yara._Cfunc_yr_compiler_get_rules(0x564c10139020, 0xc42000ec80, 0xc400000000)
	_cgo_gotypes.go:1015 +0x4f fp=0xc42005f7e8 sp=0xc42005f7b8 pc=0x564c0d9aed1f
github.com/maliceio/malice-yara/vendor/github.com/hillu/go-yara.(*Compiler).GetRules.func1(0x564c10139020, 0xc42000ec80, 0x0)
	/go/src/github.com/maliceio/malice-yara/vendor/github.com/hillu/go-yara/compiler.go:192 +0xd9 fp=0xc42005f820 sp=0xc42005f7e8 pc=0x564c0d9b57a9
github.com/maliceio/malice-yara/vendor/github.com/hillu/go-yara.(*Compiler).GetRules(0xc42006a840, 0x0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/vendor/github.com/hillu/go-yara/compiler.go:192 +0x51 fp=0xc42005f860 sp=0xc42005f820 pc=0x564c0d9b1001
main.scanFile(0xc420024500, 0x16, 0x564c0daeb7b3, 0x6, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/yara.go:116 +0x8c fp=0xc42005f930 sp=0xc42005f860 pc=0x564c0dae4f1c
main.main.func2(0xc4200c4580, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/yara.go:296 +0x17e fp=0xc42005fb28 sp=0xc42005f930 pc=0x564c0dae699e
github.com/maliceio/malice-yara/vendor/github.com/urfave/cli.HandleAction(0x564c0de355a0, 0xc420050df0, 0xc4200c4580, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/vendor/github.com/urfave/cli/app.go:490 +0xca fp=0xc42005fb50 sp=0xc42005fb28 pc=0x564c0dad415a
github.com/maliceio/malice-yara/vendor/github.com/urfave/cli.(*App).Run(0xc42009e820, 0xc42001e180, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/maliceio/malice-yara/vendor/github.com/urfave/cli/app.go:264 +0x5f0 fp=0xc42005fd28 sp=0xc42005fb50 pc=0x564c0dad2410
main.main()
	/go/src/github.com/maliceio/malice-yara/yara.go:344 +0x89b fp=0xc42005ff88 sp=0xc42005fd28 pc=0x564c0dae64fb
runtime.main()
	/usr/lib/go/src/runtime/proc.go:198 +0x21a fp=0xc42005ffe0 sp=0xc42005ff88 pc=0x564c0d6c660a
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42005ffe8 sp=0xc42005ffe0 pc=0x564c0d6f0da1

rax    0x0
rbx    0x6
rcx    0x7fe370f11f1b
rdx    0x0
rdi    0x2
rsi    0x7ffe3a5bee70
rbp    0x7ffe3a5bee70
rsp    0x7ffe3a5bee58
r8     0x2000
r9     0x3
r10    0x8
r11    0x246
r12    0xffffffffffffffff
r13    0x15e
r14    0x15d
r15    0x200
rip    0x7fe370f11f1b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by hillu** [comment]
Unfortunately, the YR_COMPILER object becomes unusable once it has run into an error. I'm afraid you'll need to abort if you detect en error in <https://github.com/malice-plugins/yara/blob/dc593215a668d229a01c7c3afdf676f814d98902/yara.go#L91>. 

Does this help?

**Comment by blacktop** [comment]
Do I need to abort everything or can I just destroy the compiler and re-create it?

**Comment by hillu** [comment]
re-creating the compiler object ought to do it.

**Comment by blacktop** [comment]
destroying and recreating did the trick 😉 

thank you for making such an awesome library 👍

**Comment by hillu** [comment]
@blacktop Thanks for pointing out that unexpected behavior to me. I have updated the documentation and introduced some workaround code so that programs no longer crash and an error is returned instead.
