### ISSUE TITLE
cgo pointer rules break ScanMem [go 1.6] 

### ISSUE THREAD

**Issue by sprungknoedl** [hillu/go-yara#5]
When scanning a byte slice with ScanMem go panics with:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 7 [running]:
panic(0x5fbd00, 0xc82000e8b0)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/hillu/go-yara._cgoCheckPointer0(0x5a9be0, 0xc820016fe4, 0x0, 0x0, 0x0, 0x54417e)
	??:0 +0x4d
github.com/hillu/go-yara.addString(0xc82000e888, 0x11b3dd4, 0x0, 0xc820016fe4, 0xc800000030)
	/home/tom/src/github.com/hillu/go-yara/rules.go:117 +0xce
github.com/hillu/go-yara._cgoexpwrap_f3bc5924bb1c_addString(0xc82000e888, 0x11b3dd4, 0x0, 0xc820016fe4, 0xc800000030)
	??:0 +0x47
github.com/hillu/go-yara._Cfunc_yr_rules_scan_mem(0x12360e0, 0xc820016fe4, 0x3b, 0x1, 0x58a900, 0xc82000e888, 0x1, 0x0)
	??:0 +0x44
github.com/hillu/go-yara.(*Rules).ScanMem(0xc82002c068, 0xc820016fe4, 0x3b, 0x40, 0x1, 0x3b9aca00, 0x0, 0x0, 0x0, 0x0, ...)
	/home/tom/src/github.com/hillu/go-yara/rules.go:147 +0x23d
```

Using a bytes.Buffer in rules_test.go/TestReader seems to trigger the above error

```diff
diff --git a/rules_test.go b/rules_test.go
index ca59966..83b912d 100644
--- a/rules_test.go
+++ b/rules_test.go
@@ -109,7 +109,10 @@ func TestReader(t *testing.T) {
        if err != nil {
                t.Fatalf("ReadRules: %+v", err)
        }
-       m, err := r.ScanMem([]byte(" abc "), 0, 0)
+
+       buf := &bytes.Buffer{}
+       buf.Write([]byte(" abc "))
+       m, err := r.ScanMem(buf.Bytes(), 0, 0)
        if err != nil {
                t.Errorf("ScanMem: %s", err)
        }
```

**Comment by sprungknoedl** [comment]
A possible fix seems to be:
```
diff --git a/rules.go b/rules.go
index c8982c8..229d4e1 100644
--- a/rules.go
+++ b/rules.go
@@ -135,7 +135,8 @@ const (
 func (r *Rules) ScanMem(buf []byte, flags ScanFlags, timeout time.Duration) (matches []MatchRule, err error) {
        var ptr *C.uint8_t
        if len(buf) > 0 {
-               ptr = (*C.uint8_t)(unsafe.Pointer(&(buf[0])))
+               ptr = (*C.uint8_t)(unsafe.Pointer(C.CString(string(buf))))
+               defer C.free(unsafe.Pointer(ptr))
        }
        id := callbackData.Put(&matches)
        defer callbackData.Delete(id)
```

but I'm not sure of the exact implications

**Comment by hillu** [comment]
Thank you for reporting the bug, I am investigating.

`C.CStrin()` would certainly make a copy which I'd like to avoid.

**Comment by hillu** [comment]
Sorry, I can't reproduce the issue with
<pre>
$ go version
go version go1.6.3 linux/amd64
</pre>
Are you sure that you are using the current master 8fe44928b951ff9953459db42c5df1a08b1bb409 ?

**Comment by sprungknoedl** [comment]
Hi,

yes I'm using the current master:
```
$ git rev-parse HEAD
8fe44928b951ff9953459db42c5df1a08b1bb409
```

my Go version is also identical to yours ...
```
$ go version
go version go1.6.3 linux/amd64
```

Maybe different yara or gcc versions are used?

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160707 (GCC)
```
```
$ yara -v
yara 3.4.0
```

**Comment by hillu** [comment]
yara or gcc versions should not matter.

I have yara 3.5.0 (3.5.0-1 from Debian) and gcc version 6.1.1 20160802 (Debian 6.1.1-11)  installed. Weird.

**Comment by dahawk** [comment]
Hi,

I also tried the test with the patch and could produce the same result on an Ubuntu 16.04

```
$ go version
go version go1.6.2 linux/amd64
```
```
$ yara -v
yara 3.4.0
```
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
```

resulting in
```
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
	panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 5 [running]:
panic(0x592160, 0xc82000e9f0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc820018090)
	/usr/lib/go-1.6/src/testing/testing.go:467 +0x192
panic(0x592160, 0xc82000e9f0)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/hillu/go-yara._cgoCheckPointer0(0x553fa0, 0xc82001a335, 0x0, 0x0, 0x0, 0x4)
	??:0 +0x4d
github.com/hillu/go-yara.addString(0xc82000e988, 0x1d56466, 0x1, 0xc82001a335, 0xc800000003)
	/home/christof/workspace/src/github.com/hillu/go-yara/rules.go:117 +0xce
github.com/hillu/go-yara._cgoexpwrap_f3bc5924bb1c_addString(0xc82000e988, 0x1d56466, 0x1, 0xc82001a335, 0x3)
	??:0 +0x47
github.com/hillu/go-yara._Cfunc_yr_rules_scan_mem(0x1d28ab0, 0xc82001a334, 0x5, 0x0, 0x539940, 0xc82000e988, 0x0, 0x0)
	??:0 +0x44
github.com/hillu/go-yara.(*Rules).ScanMem(0xc820030068, 0xc82001a334, 0x5, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/christof/workspace/src/github.com/hillu/go-yara/rules.go:147 +0x23d
github.com/hillu/go-yara.TestReader(0xc820018090)
	/home/christof/workspace/src/github.com/hillu/go-yara/rules_test.go:114 +0x37a
testing.tRunner(0xc820018090, 0x8ad8b8)
	/usr/lib/go-1.6/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/lib/go-1.6/src/testing/testing.go:582 +0x892
exit status 2
```

**Comment by sprungknoedl** [comment]
When running the *original* tests with `GODEBUG=cgocheck=2` to enable "complete checking of pointer handling, at some cost in run time", it fails while reading the rules:

```
$ GODEBUG=cgocheck=2 go test -run TestReader
write of Go pointer 0xc82008c4a8 to non-Go memory 0x9e6c00
fatal error: Go pointer stored into non-Go memory

runtime stack:
runtime.throw(0x5f9e20, 0x24)
	/usr/lib/go/src/runtime/panic.go:547 +0x90
runtime.cgoCheckWriteBarrier.func1()
	/usr/lib/go/src/runtime/cgocheck.go:44 +0xae
runtime.systemstack(0x8bd500)
	/usr/lib/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1051

goroutine 20 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:245 fp=0xc820025518 sp=0xc820025510
runtime.cgoCheckWriteBarrier(0x9e6c00, 0xc82008c4a8)
	/usr/lib/go/src/runtime/cgocheck.go:45 +0x9f fp=0xc820025548 sp=0xc820025518
runtime.writebarrierptr(0x9e6c00, 0xc82008c4a8)
	/usr/lib/go/src/runtime/mbarrier.go:132 +0x2b fp=0xc820025578 sp=0xc820025548
github.com/hillu/go-yara.ReadRules(0x7f1ad8540510, 0xc82008e058, 0x0, 0x0, 0x0)
	/home/tom/src/github.com/hillu/go-yara/rules.go:240 +0x4ce fp=0xc820025630 sp=0xc820025578
github.com/hillu/go-yara.TestReader(0xc8200b6000)
	/home/tom/src/github.com/hillu/go-yara/rules_test.go:108 +0x1a5 fp=0xc820025778 sp=0xc820025630
testing.tRunner(0xc8200b6000, 0x8adab8)
	/usr/lib/go/src/testing/testing.go:473 +0x98 fp=0xc8200257b0 sp=0xc820025778
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200257b8 sp=0xc8200257b0
created by testing.RunTests
	/usr/lib/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0x61b110, 0x8ad8c0, 0x19, 0x19, 0xc82006c001)
	/usr/lib/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82004bef8, 0x5d3220)
	/usr/lib/go/src/testing/testing.go:515 +0x81
github.com/hillu/go-yara.TestMain(0xc82004bef8)
	/home/tom/src/github.com/hillu/go-yara/main_test.go:14 +0x73
main.main()
	github.com/hillu/go-yara/_test/_testmain.go:100 +0x114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1
```

Wrappers for C code are not fun anymore with 1.6 :(

**Comment by hillu** [comment]
Thank you.  At least, now I have something that I can reproduce...

**Comment by hillu** [comment]
So far, I can reproduce the original issue that involves the `addString` callback in an Ubuntu xenial chroot.
<pre>
$ go version
go version go1.6.2 linux/amd64
$ gcc -v
[...]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
</pre>
The statement which causes the pointer check to fail seems to be
<pre>
C.GoBytes(data, length)
</pre>

**Comment by hillu** [comment]
YARA 3.5 differs from YARA 3.4 in that it passes a copy of the data to the callback function. Thus, `C.GoBytes` is called with a pointer to data generated in C-land instead of a pointer into `[]byte` that was generated by `buf.Bytes()`.

@sprungknoedl can you please verify that your problem goes away when upgrading YARA to 3.5?

I fail to see why there is a need for checking pointers when calling `C.GoBytes` and I have no idea why some  random data is interpreted as a (possibly) valid pointer.

**Comment by sprungknoedl** [comment]
Can't reproduce any of the panics with the current commit and yara 3.5.0 :+1:

**Comment by hillu** [comment]
@sprungknoedl What about the current commit and YARA 3.4.0?

YARA 3.5.0 introduced a change where a copy of the matched data is passed to the callback functions instead of a pointer into the scanned buffer, so even without my fix, the problem did not occur with YARA 3.5.0.

**Comment by sprungknoedl** [comment]
commit | yara 3.4.0 | yara 3.5.0
----------|---------------|-------------
8fe4492 (before #5) | **panic** | pass
c36c17b (master) | pass | pass

**Comment by hillu** [comment]
Perfect! Thank you very much.

I wonder what will break with Go 1.7 and beyond...
